site_name: PerilKeeper
site_description: "PerilKeper — code-centric way to manage cybersecurity, safety and quality risks."
site_url: https://perilkeeper.dev
repo_url: https://github.com/mkalkov/perilkeeper.dev

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - search.suggest
    - search.highlight
    - header.autohide
  palette:
    - scheme: default
      primary: custom
      accent: custom
    - scheme: slate
      primary: custom
      accent: custom
  logo: assets/favicon.png
  favicon: assets/favicon.ico

extra_css:
  - assets/styles/brand.css

nav:
  - Home: index.md
  - Language: language.md
  - Examples: examples.md
  - Use cases: use-cases.md
  - Architecture: architecture.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.tilde
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mkalkov/perilkeeper.dev
  analytics:
    provider: plausible
    domain: perilkeeper.dev
  meta:
    - property: og:site_name
      content: Perilkeeper
    - property: og:image
      content: https://perilkeeper.dev/assets/favicon.png
    - name: theme-color
      content: "#243447"
